### ISSUE TITLE
grid.diff dropping coordinates

### ISSUE THREAD

**Issue by ALDepp** [xgcm/xgcm#150]
Hi all,  I am wondering about the behaviour of grid.diff. 

For example, when I find the differences of a variable ds.DIA_IMPVF_TEMP, output:

<xarray.DataArray 'DIA_IMPVF_TEMP' (time: 1, z_w_bot: 62, nlat_t: 305, nlon_t: 1301)>
dask.array<shape=(1, 62, 305, 1301), dtype=float32, chunksize=(1, 62, 305, 1301)>
Coordinates:
  * z_w_bot  (z_w_bot) float32 1000.0 2000.0 3000.0 ... 574999.06 599999.06
    TLONG    (nlat_t, nlon_t) float64 dask.array<shape=(305, 1301), chunksize=(305, 1301)>
    TLAT     (nlat_t, nlon_t) float64 dask.array<shape=(305, 1301), chunksize=(305, 1301)>
  * time     (time) object 0052-01-16 05:17:48
  * nlon_t   (nlon_t) float64 0.5 1.5 2.5 3.5 ... 1.298e+03 1.3e+03 1.3e+03
  * nlat_t   (nlat_t) float64 0.5 1.5 2.5 3.5 4.5 ... 301.5 302.5 303.5 304.5
Attributes:
    grid_loc:      3113
    long_name:     TEMP Flux Across Bottom Face from Diabatic Implicit Vertic...
    cell_methods:  time: mean
    units:         degC cm/s

with grid.diff(ds.DIA_IMPVF_TEMP, axis="Z", boundary="extend")
 the coordinates TLONG and TLAT and the attributes are dropped. 
output:
<xarray.DataArray 'sub-bf9600c57ef24f7ffb1ba1512c2a9276' (time: 1, z_t: 62, nlat_t: 305, nlon_t: 1301)>
dask.array<shape=(1, 62, 305, 1301), dtype=float32, chunksize=(1, 1, 305, 1301)>
Coordinates:
  * time     (time) object 0052-01-16 05:17:48
  * z_t      (z_t) float32 500.0 1500.0 2500.0 ... 537500.0 562499.06 587499.06
  * nlat_t   (nlat_t) float64 0.5 1.5 2.5 3.5 4.5 ... 301.5 302.5 303.5 304.5
  * nlon_t   (nlon_t) float64 0.5 1.5 2.5 3.5 ... 1.298e+03 1.3e+03 1.3e+03

Is this intentional, and is there a way to retain the extra info?

**Comment by rabernat** [comment]
Hello and welcome to xgcm! Thanks so much for raising an important issue. 

Yes: for now this is intentional. Xgcm drops all non-dimension coords from the inputs immediately. This makes alignment of slices less error prone and expensive.

However, if users find this inconvenient, we could consider changing this behavior. At the very least, the behavior should be well documented in the docs.

In my own personal experience, I usually don’t miss the dropped coords. They are always still accessible from the parent dataset.

**Comment by jbusecke** [comment]
One can also 'reassign' the resulting array to the parent dataset by doing something like `ds['new_variable'] = grid.diff(ds['old_variable'], 'Y')`. 

That way I believe all compatible coordinates are available when calling `ds['new_variable']`. 

I have had much trouble with some coordinates in the past and would like to retain this behavior as a default. But if you find the above workflow not suitable, we could think about an optional `keep_attrs=True` argument?

**Comment by dcherian** [comment]
This sounds like an xarray annoyance, so it would be great if you could open an upstream issue with an example.

**Comment by jbusecke** [comment]
This has been one of these 'diffuse' problems that I had trouble condensing into a simplified example (since dropping the coords helped most of the time, I didn't bother too much after that). But I will certainly keep this in mind and try to submit an issue when I experience this again.

**Comment by ALDepp** [comment]
> One can also 'reassign' the resulting array to the parent dataset by doing something like `ds['new_variable'] = grid.diff(ds['old_variable'], 'Y')`.


Thanks for the tip! I'll try that.

**Comment by rabernat** [comment]
Thanks @dcherian! I saw that in xarray-fantastic!

Would you be game to do a PR to remove the coordinate-dropping from xgcm? If so, should we require a minimum xarray version going forward to ensure good performance?

**Comment by jbusecke** [comment]
Oh this would be very helpful for some of my current workflows! 

I could help too (tomorrow) if @dcherian is too busy.

**Comment by dcherian** [comment]
@jbusecke Go for it!  

It'll require some testing to be sure that it's an improvement across the board. For example, there is still an indexing bug (https://github.com/pydata/xarray/issues/2227#issuecomment-533193480) that leads to unnecessary alignments but the unnecessary computes issue is definitely fixed (https://github.com/pydata/xarray/issues/3454)

>  If so, should we require a minimum xarray version going forward to ensure good performance?

Absolutely. It would be painful otherwise.

**Comment by apatlpo** [comment]
hi all, what's the status on this?
Is any help needed?

**Comment by jbusecke** [comment]
Hi @apatlpo, if you have bandwidth to submit a PR, that would be much appreciated. 
I am very busy these last days. I would be happy to give pointers and feedback.

My preference would be an additional keyword (e.g. `grid.diff(keep_coords=True)`, which is off by default to avoid breaking old code). What do you think @rabernat?

**Comment by apatlpo** [comment]
Sure, I can give it a shot.

**Comment by jbusecke** [comment]
> > If so, should we require a minimum xarray version going forward to ensure good performance?

> Absolutely. It would be painful otherwise.

@dcherian which version should we be requiring for this? Is `0.14` sufficient? Or do we need `0.15`?

**Comment by dcherian** [comment]
`0.14.1`

**Comment by kthyng** [comment]
Hi! I came across this issue look for more information about dropping coords over `grid` object operations in xgcm. Let me know if I should start a different issue instead of writing here.

I have upgraded and tried the new `keep_coords=True` option, but it appears to only work for 1D coords. I am using ROMS and have 1D, 2D, 3D, or 4D coords associated with variables depending on the variable. Is it in the purview of xgcm to consider tracking coords like xarray does? I consider this to be a big advantage of using xarray. I don't know the guts of xgcm, but I would guess that since the grid object tracks where variables are located on the staggered C grid, coords could similarly be tracked along grid operations like derivative.

**Comment by jbusecke** [comment]
Hi @kthyng , thanks for using xgcm. 

do you have a simple example I could take a look at? Even a screenshot of the dataset/dataarray before and after manipulation with xgcm could help. 

I think it would be best to open a clean issue, just to keep things organized. Then we can also close this one here.

**Comment by jbusecke** [comment]
Sorry I didnt mean to close yet. Please feel free to close when you have the new issue open.

**Comment by kthyng** [comment]
(I can't close this issue — it was just open when I came along)

**Comment by jbusecke** [comment]
Ok thanks for letting me know. I'll close this now.
