### ISSUE TITLE
Interpolating from D-grid to C-grid

### ISSUE THREAD

**Issue by nbren12** [xgcm/xgcm#169]
Hi @rabernat. I'm loving this package, btw.

We are using it to handle cubedsphere data from FV3, which uses a D-grid staggering. Unlike C-grid, D-grid staggering has x-wind located on the y-face, which is useful for computing vorticity. However, to advect scalars one typically interpolates this data to C-grid. It is simple to interpolate the D-grid winds to cell-centers, but `interpolate_2d_grid` raises an not implemented error when I try to interpolate from the cell-centered winds to the C-grid. Do you know a workaround for this?

**Comment by rabernat** [comment]
Hi @nbren12 - thanks for the issue and sorry for the slow reply.

This is a known issue, which I started working on in #117. Since then I have thought about some better ways to do it, but have not had time.

Bottom line, yes, it should be supported, but is a kind of nasty edge case that no one has stepped up to solve yet. Hopefully once we hire some people for our Moore foundation grant, we can finally get to it. Or if you're motivated, PR welcome! ;)

For reference:
![d-grid](https://upload.wikimedia.org/wikipedia/commons/thumb/8/8a/Discretization_for_the_different_Arakawa_grids_correct.svg/1000px-Discretization_for_the_different_Arakawa_grids_correct.svg.png)

The challenge lies in figuring out how to identify the proper halos for the velocity points. I believe these fail cases occur on corner points where you need to pull halo values from two different faces.
