### ISSUE TITLE
apply Grid.average to subset of data

### ISSUE THREAD

**Issue by miniufo** [xgcm/xgcm#193]
I constructed a Grid object from a lat/lon Dataset `dset`.  When I tried the following codes, I found a huge difference that is totally unexpected:
```python
# ssta is a global 2D field in dset, subregion is the Nino 3.4 region
# unweighted mean
print(ssta.sel(subregion).mean(['yt_ocean', 'xt_ocean']).values)

# weighted mean
print(grid.average(ssta.sel(subregion), ['X', 'Y']).values)
```
The outputs are:
```python
# unweighted mean
[ 1.9443461  1.7437879  1.012453  ... -1.6583643 -1.8293577 -2.0875595]

# weighted mean
[ 0.02257358  0.02026701  0.01267836 ... -0.01836029 -0.02009966
 -0.02342124]
```

I know that these two ways of mean will yield slightly different results but here the difference is quite large.  So I would ask:
1. If the DataArray passed in is only a subset (subregion) of the full domain (as in this example), will the `Grid` object do the average properly?
2. Do other `Grid` functions (e.g., interp, integrate, cumsum etc.) take into account this along any dimension combination?

This is the info for the `dset`:
```python
In [44]: dset
Out[44]: 
<xarray.Dataset>
Dimensions:        (time: 1200, xt_ocean: 360, xt_ocean_left: 360, yt_ocean: 200, yt_ocean_left: 200)
Coordinates:
    geolat_t       (yt_ocean, xt_ocean) float32 -81.5 -81.5 ... 65.21032
    geolon_t       (yt_ocean, xt_ocean) float32 -279.5 -278.5 ... 79.98032
  * yt_ocean       (yt_ocean) float64 -81.5 -80.5 -79.5 -78.5 ... 87.5 88.5 89.5
  * xt_ocean       (xt_ocean) float64 -279.5 -278.5 -277.5 ... 77.5 78.5 79.5
  * time           (time) object 0101-01-16 12:00:00 ... 0200-12-16 12:00:00
  * xt_ocean_left  (xt_ocean_left) float64 -280.0 -279.0 -278.0 ... 78.0 79.0
  * yt_ocean_left  (yt_ocean_left) float64 -82.0 -81.0 -80.0 ... 87.0 88.0 89.0
    dxG            (yt_ocean, xt_ocean_left) float64 1.644e+04 ... 970.4
    dyG            (yt_ocean_left, xt_ocean) float64 nan nan ... 1.112e+05
    dxC            (yt_ocean, xt_ocean) float64 1.644e+04 1.644e+04 ... 970.4
    dyC            (yt_ocean, xt_ocean) float64 1.112e+05 1.112e+05 ... nan nan
    rAc            (yt_ocean, xt_ocean) float64 1.828e+09 1.828e+09 ... nan nan
Data variables:
    ssta           (time, yt_ocean, xt_ocean) float32 ...
```

**Comment by raphaeldussin** [comment]
my bet is on bottom land points taken into account in the denominator

**Comment by jbusecke** [comment]
> If the DataArray passed in is only a subset (subregion) of the full domain (as in this example), will the Grid object do the average properly?

Nope. It will blindly broadcast the array to the metric and thus count metric points where there is no data. You have to create a new grid object for that. 

I was aware of this being a bit of an annoyance, but wanted to see if we can use the functionality in [xarrays `weighted`](https://xarray.pydata.org/en/v0.15.1/computation.html#weighted-array-reductions) to improve this behavior. Ill have to look into this some time in the future, but thanks for raising the issue. 

Perhaps we can see if we can implement this together with #111

**Comment by dcherian** [comment]
> It will blindly broadcast the array to the metric and thus count metric points where there is no data. You have to create a new grid object for that.

I think you mean "align"? and can't we control this by setting `join="inner"` so that it will subset the metric to the data?

**Comment by dcherian** [comment]
Ah I was wrong. Apologies. You shouldn't be able to create a grid from the "wrong subset" but all computations should work?

Why do we want to disable this workflow?

**Comment by jbusecke** [comment]
Two things: 
1) the two examples you showed should be perfectly fine. One would get an 'outer' attribute (`len(x_g) == len(x_c)+1`). The former is the 'standard' dataset in my opinion. 

2) We would not deactivate the workflow, rather than thinking about if we allow it. As @miniufo showed, using a subset of the data with a grid object created on another dataset produces nonsense. I personally think that a grid object should always belong to dataset. I can just see a lot of confusion arising from allowing to throw in other datasets...but maybe I am also to negative. This is why I wanted to encourage a discussion. 

Lets explore the example above: What exactly speaks against creating a new grid object?

```
# ssta is a global 2D field in dset, subregion is the Nino 3.4 region
# unweighted mean
ssta_sub = ssta.sel(**subregion)
grid_sub = Grid(ds_sub, ...)


print(ds_sub.mean(['yt_ocean', 'xt_ocean']).values)

# weighted mean
print(grid_sub.average(ssta_sub, ['X', 'Y']).values)
```

With the average this should work pretty much out of the box, except that we have to put in the metrics again. But the naming has not changed, hence that should be trivial?

An alternative suggestion to handle these kind of situations would be to have something like `.sel()/.isel()` implemented in grid: 
`grid_sub, ds_sub = grid.sel(region)`

**Comment by dcherian** [comment]
> a subset of the data with a grid object created on another dataset produces nonsense.

My questions is: Could this be fixed with `metric_vars = xr.align(array, *metric_vars, join="inner")[1:]` in `get_metric`? This will reindex all metric variables to the `array`. 

Since `array` is a subset of the grid; there are well defined metric values at all subset-points. So the calculation still works?

**Comment by jbusecke** [comment]
Ok I see. I will have to think about that, and would also like to hear what @rabernat thinks about this. @miniufo does the workaround above work for your purposes in the meantime?

**Comment by dcherian** [comment]
`join="left"` might be most appropriate actually. This will use the indexes of `array` to reindex the metric variables.

**Comment by miniufo** [comment]
Ops, I didn't realize that the root of the problem is the automatic alignment of `xarray`.  This is a magic part of `xarray` but I think this is a case I would perfer to have it switched off.

> @miniufo does the workaround above work for your purposes in the meantime?
I tried the `grid_sub` way and it works fine except that when the field contains all nans, the returned average value is zero.  Is this a bug in xgcm?

Since what I've done here is very common in climate research e.g., get a global SST and average over a subregion to calculate climate index with proper area-weighting, I would like to suggest a solution like:
```python
# a dict-like arg for DataArray.sel()
subregion = {'X': slice(100, 200), 'Y': slice(-10, 10)}
grid.average(ssta, axis=subregion)
```
which would be literally similar to
```python
# this is not working correctly
grid.average(ssta.sel(subregion), axis=['X', 'Y'])
```
This is user-friendly and easy to implement.  Internally, we can use either `xarray.weighted` or `grid_sub` way to do this.  This may also be extended to other reduction operation in `xgcm` like `sum`, `cumsum`, `integrate` to accept a subset of full data.  In this way, we don't need to accept a subset of data and avoid checking the dimension of a subset (issue #111).

> An alternative suggestion to handle these kind of situations would be to have something like `.sel()/.isel()` implemented in grid: `grid_sub, ds_sub = grid.sel(region)`

I also like this solution because it makes `grid` object more interoperatable with `xarray` (`grid` is essentially a `Dataset` of metrics!).

So just to be sure which is better?  I would like to contribute in some way.  Now I am getting myself used to github so I can collaborate with you guys.

**Comment by jbusecke** [comment]
Awesome that you want to get involved @miniufo! 

But I think we need to unpack these problems a bit more and address these as the smallest possible units: 

There are several issues we are encountering in your example: 

1) xgcm as of now, requires metrics to match datasets in terms of missing values! If you pass a metric that has a value, where the data doesnt, results will come out wrong. This should **absolutely** be improved. My idea was to refactor the internals [here](https://github.com/xgcm/xgcm/blob/03c165c225545e5bb4aa22eb08ad9a366b4879e3/xgcm/grid.py#L1102-L1110) using `xarray.weighted` (or some if its internals; I have yet to take a look at it), instead of just multiplying the metric with the data, since that internal logic takes care of properly aligning missing values.

2) A related issue was raised in #182, where @rabernat suggested, that we could implement masks in a similar fashion as metrics in the data model of xgcm. This would also allow accounting for partial cells as used in e.g. mitgcm and mom5. I think this is also a worthwhile addition. It does somewhat overlap with 1) but would not actually interfere with one another, I believe.

3) How should all of these things work on a subset of the data. Personally this has the least priority for me, since I still think creating a new grid object would be the way to go, but that is a personal opinion atm, and I think you both are making some good points as to why we might want to implement this in the future. 

Do you think that you would want to address 1)? I am happy to provide some guidance on that. Before you start, I however really would like to get some feedback from @rabernat, if he hears us?

**Comment by miniufo** [comment]
Now I understand better with the problem and possible solutions.

> join="left" might be most appropriate actually. This will use the indexes of array to reindex the metric variables.

So @dcherian 's suggestion to align metrics to a subset of data would also fail to give the right answer if the sub-metrics do not match the sub-data in terms of missing values, right?

> Do you think that you would want to address 1)? I am happy to provide some guidance on that.

Yes I would like to if I understand it completely (do need your guidance).  But I don't really get the internals of `xarray.weighted`.  What is the main difference between `xarray.weighted` internals and `weighted = array * mask`?

**Comment by jbusecke** [comment]
> So @dcherian 's suggestion to align metrics to a subset of data would also fail to give the right answer if the sub-metrics do not match the sub-data in terms of missing values, right?

I believe this is true.

> Yes I would like to if I understand it completely (do need your guidance). But I don't really get the internals of xarray.weighted. What is the main difference between xarray.weighted internals and weighted = array * mask?

I am not sure about this either. I just read the examples and it takes into account mismatches between data and weights in terms of missing values. You (we) would have to dive into how xarray implements this, since you also want to 'unweight' the data correctly. I am quite busy over at [cmip6_preprocessing](https://github.com/jbusecke/cmip6_preprocessing) these days, but hopefully can turn my attention back to xgcm towards the end of the week.

**Comment by Thomas-Moore-Creative** [comment]
The coming #259 "bug fix" will be very welcome. As a new user, yesterday I was convinced I had done something wrong with setting up the xgcm grid when a test of a 2D spatial average of a smaller selected region was clearly way off.  Thanks for this coming fix, @jbusecke et al.

**Comment by jbusecke** [comment]
@Thomas-Moore-Creative please note that #259 only solves the issue of a subset for `grid.average` and we do not recommend to use it in this way currently. The recommended way to compute subsets is to create a new grid object on the subset.
It works though! Just be careful.

**Comment by jbusecke** [comment]
Can we close this and have subsequent discussions over at #200 ?
