### ISSUE TITLE
halo points extension of DataArrays on tiled grids

### ISSUE THREAD

**Issue by apatlpo** [xgcm/xgcm#201]
follows OceanParcels/parcels#548

Could xgcm be leveraged to generate expanded DataArrays that contain halo points from other faces (I am typically thinking about llc type grids)?
Or does it go against the library philosophy?

This would be useful to distribute custom calculations over such grids.

**Comment by jbusecke** [comment]
Thanks for bringin this up. I think this fits into a broader discussion (see #194), but @rabernat is the wizard of face connections. So he would be the better person to answer this question.

**Comment by jbusecke** [comment]
@rabernat just pinging you here again. Should we orgnize a project to generally work on the face connection more? There are a few issues flying around that seem related to me.

**Comment by rabernat** [comment]
I think this is an interesting and useful concept. It would be useful not only for Lagrangian particles but also for things like vorticity, gradients, which require a stencil.

Dask's concept of [Ghost cells](http://dask.readthedocs.org/en/latest/ghost.html) could be very useful. The challenge would be to populate the Ghost cells using custom logic, rather than the default assumptions.

It is not against the library philosophy, but I think it would be hard to implement. We would need to discuss the design carefully and figure out what sort of effort is required.

**Comment by jbusecke** [comment]
Will this potentially be addressed by #344?
