### ISSUE TITLE
Adding basic benchmarking to CI [FEATURE]

### ISSUE THREAD

**Issue by jbusecke** [xgcm/xgcm#238]
I think it would be helpful to have an additional testing module, where we benchmark some operations with xgcm. 

I am thinking of having a few test functions that operate on one 'sizeable' synthetic test fixture and apply simple operations on it. I think these should be relatively high level actions like computing a derivative or transforming vertical coordinates. This way we at least have a rough idea of how changes we make impact the performance.

I have found [pytest-benchmark](https://github.com/ionelmc/pytest-benchmark) and some related [github action](https://github.com/rhysd/github-action-benchmark), that seem to give us the functionality to run these relatively elegantly and track results in the CI.

I am completely new to this, but I am sure we need to fiddle around to ensure that these tests are always run on e.g. the same hardware and other factors to ensure comparability...

If anyone here has experience with this sort of testing I would greatly appreciate input on both the framework (pytest-benchmark) and the implementation.

**Comment by rabernat** [comment]
[Airspeed Velocity](https://asv.readthedocs.io/) is the standard tool used in the scientific python ecosystem.

**Comment by jbusecke** [comment]
That looks very cool. From a quick read I have several questions: 

1. We need a webserver to host the results. Where would we put them ideally? I guess we could just make a github-pages in the xgcm orgnization?
2. We need one or several machines with consistent hardware to run these tests. I have been looking at some of the benchmarks of [dask/pandas/xarray and co](https://pandas.pydata.org/speed/), but am pretty clueless how to set this up.

Is there any guide out there how to approach this best? Pinging @hamman, since he seems to have been involved in setting this up for [xarray](https://github.com/pydata/xarray/pull/1457) a while back.

**Comment by jhamman** [comment]
I did do some of the setup on the xarray side but, IIRC, @TomAugspurger holds the keys to the Pandas/Xarray/Dask Airspeed Velocity hardware and did the hardware configuration for us. You can see everything I did in the Xarray repo. As I understand it, there is a dedicated machine that belongs to the Pandas project for this somewhere (maybe in Tom's garage or something).   I would think it possible to set something similar up on a university server somewhere.

**Comment by jbusecke** [comment]
> As I understand it, there is a dedicated machine that belongs to the Pandas project for this somewhere (maybe in Tom's garage or something)

😂 Thats awesome actually! 

But you think this is not feasible to run anywhere in the cloud?

**Comment by TomAugspurger** [comment]
When setting this up a few years ago, we were told that trying to detect
regressions on the cloud would be too noisy. It might catch large slowdowns
but would have too many false positives for smaller "regressions" that
vanish in the next commit to be worthwhile. None of us actually verified
that though.

The scripts that set up pandas' benchmark server are supposed to be at
https://github.com/asv-runner/asv-runner, but I've made manual updates that
aren't reflected there. But the basic idea is

* supervisord to automatically start up airflow
* daily airflow jobs that run ASV benchmarks for pandas + a couple other
projects
* push those results somewhere (pandas has a webserver, ASV can also
publish to github-pages)

I'd offer to run xgcm's there as well, but you should consider that a last
resort given how flakey the setup is. They apparently haven't run in a few
weeks, probably because I forgot to turn it on after we lost power.

**Comment by jbusecke** [comment]
@rabernat , do you think that we could/should run this on one of the Lamont machines?

**Comment by rabernat** [comment]
I think we should explore the cloud options before ruling them out. I have no desired to maintain a dedicated server for this. Our existing local machines are not suitable since they have highly variable usage by multiple users, so likely much *more* noisy than a cloud VM. Tom's machine is literally just for that purpose.

**Comment by jbusecke** [comment]
Understood. Since I am still not very familiar with cloud internals, is there anybody who might be willing to give me some pointers?

**Comment by rabernat** [comment]
The basic workflow would involve a github workflow like this
- An action to build a docker container with the specific version / commit of xgcm + depdencies for ASV
- An action to run this container in google cloud or AWS in a specific VM configuration and extract the results
- Posting the results back to the PR and triggering a pass / fail

**Comment by rabernat** [comment]
@charlesbluca has become something of a cloud / CI expert, so he might have ideas.

**Comment by TomAugspurger** [comment]
Depending on your desires, a slightly simpler option would be to run these
as part of CI. You'd install your project normally (like for tests) and asv.

Then you'd run `asv continuous master HEAD`

That'll print out info on whether the benchmark changed. You could parse
that output to fail if there's too large of a regression. Hopefully since
they're running in a single container things will be comparable (though
it's on a VM, so it could be a bit noisy).

The downside is that you won't have a history that could be tracked. It
would only be comparing two snapshots.

**Comment by rabernat** [comment]
FWIW, I don't feel that benchmarking is an urgent priority for xgcm right now. I think there are higher-impact tasks enumerated in our issue tracker. Enhanced documentation and tutorials come to mind.

**Comment by jbusecke** [comment]
Agreed, not a high priority. 

My two cents: It seems like it will require more communication and planning from my side than other issues. Thinking strategically I think its worth having this discussion early. Its not taking to much bandwidth from me rn.

**Comment by dcherian** [comment]
At 0th order, set it up on your laptop and run before you release :)

**Comment by jbusecke** [comment]
> At 0th order, set it up on your laptop and run before you release :)

Def planning on doing that one of these nights. Frustration levels will depend on how Denver plays hahaha.
