### ISSUE TITLE
average on cubed sphere grid

### ISSUE THREAD

**Issue by AaronDavidSchneider** [xgcm/xgcm#290]
Hi,

I have been experimenting with `xgcm` the past days. Using the cubed sphere grid from MITgcm I can create a grid object in xgcm using the following `face_connections` (following http://svante.mit.edu/~jscott/html/phys_pkgs/exch2.html, Fig. 5.4):

```py
def init_grid(grid_files="../run/grid.t{:03d}.nc"):
    grid_list = [xr.open_dataset(grid_files.format(i)) for i in range(1, 7)]
    grid_nc = xr.concat(grid_list, dim=range(6))
    face_connections = {'concat_dim':
                            {0: {'X': ((4, 'Y', False), (1, 'X', False)),
                                 'Y': ((5, 'Y', False), (2, 'X', False))},
                             1: {'X': ((0, 'X', False), (3, 'Y', False)),
                                 'Y': ((5, 'X', False), (2, 'Y', False))},
                             2: {'X': ((0, 'Y', False), (3, 'X', False)),
                                 'Y': ((1, 'Y', False), (4, 'X', False))},
                             3: {'X': ((2, 'X', False), (5, 'Y', False)),
                                 'Y': ((1, 'X', False), (4, 'Y', False))},
                             4: {'X': ((2, 'Y', False), (5, 'X', False)),
                                 'Y': ((3, 'Y', False), (0, 'X', False))},
                             5: {'X': ((4, 'X', False), (1, 'Y', False)),
                                 'Y': ((3, 'X', False), (0, 'Y', False))}}}

    coords = {'X': {'center': 'X', 'outer': 'Xp1'}, 'Y': {'center': 'Y', 'outer': 'Yp1'}, 'T': {'center': 'T'},
              'Z': {'center': 'Z', 'left': 'Zl'}}

    grid_nc['drW'] = grid_nc.HFacW * grid_nc.drF  # vertical cell size at u point
    grid_nc['drS'] = grid_nc.HFacS * grid_nc.drF  # vertical cell size at v point
    grid_nc['drC'] = grid_nc.HFacC * grid_nc.drF  # vertical cell size at tracer point
    metrics = {
        ('X',): ['dxC', 'dxG'],  # X distances
        ('Y',): ['dyC', 'dyG'],  # Y distances
        ('Z',): ['drW', 'drS', 'drC'],  # Z distances
        ('X', 'Y'): ['rA', 'rAz', 'rAs', 'rAw']  # Areas
    }

    grid = xgcm.Grid(grid_nc, face_connections=face_connections, coords=coords, periodic=['X', 'Y'], metrics=metrics)
    return grid
```
Yields the grid:
```
<xgcm.Grid>
X Axis (periodic, boundary=None):
  * center   X --> outer
  * outer    Xp1 --> center
Y Axis (periodic, boundary=None):
  * center   Y --> outer
  * outer    Yp1 --> center
T Axis (not periodic, boundary=None):
  * center   T
Z Axis (not periodic, boundary=None):
  * center   Z --> left
  * left     Zl --> center
```

I successfully averaged vertical coordinates: `T_average = grid.average(ds["Temp"],axis="Z")`

I would now love to calculate zonal means of the wind speed (and plot as a function of latitude). However, I am not sure if this is even possible with `xgcm`, since the physical coordinates (`XC` and `YC`) depend on (`X`, `Y`, `concat_dim`). For example:
```zonal_mean = grid.average(ds["Temp"],axis="X")```
is not the zonal mean but the mean in `X` direction (still dependent on `Y` and `concat_dim` and not on the latitude, since the latitude coordinate on the cs grid depends on X and Y).

Does it even make sense to do this with xgcm? I really like the idea of xgcm, but I currently suffer to understand how to use it with the cube sphere grid.

An alternative would be the approach by https://github.com/JiaweiZhuang/cubedsphere/blob/master/cubedsphere/util.py (which I have yet to try) or to regrid the data to a rectengular lonlat-grid and take averages thereafter.

**Comment by jbusecke** [comment]
Hi @AaronDavidSchneider, 

this is a very interesting problem, indeed. I do not have much experience with cubed-sphere grids, that part of xgcm has traditionally been @rabernat s domain.

The current approach we use does require physical dimensions to be mostly aligned with the logical index, like in this case for the vertical. Id imagine one could flip/rotate the side faces to kind of get this working, but the real problem would be incorporating the polar faces. In those in particular the physical coordinates are roughly oriented in circles (right?) around the center, and I dont think we can operate on these without some sort of regridding or binning (which is what https://github.com/JiaweiZhuang/cubedsphere/blob/master/cubedsphere/util.py does if I understood this right). 

Those sort of operations are currently out of scope for xgcm, at least in my opinion. But it would be nice to have a workflow that uses e.g. [xESMF](https://github.com/JiaweiZhuang/cubedsphere/blob/master/cubedsphere/util.py) to regrid to a regular lon/lat grid, and then operate seamlessly with xgcm. If that is something you would consider I think that an example of something like what you are doing would go a long way. We can then see where things cause friction.

Note that this problem seems to be exclusive to averaging/integrating. Things like interpolation/derivatives should still be possible (but might not work with xgcm yet) since this is something the models does internally all the time.

**Comment by AaronDavidSchneider** [comment]
Hi @jbusecke,

thanks for your detailed reply! This really helps. 

> In those in particular the physical coordinates are roughly oriented in circles (right?) around the center, and I dont think we can operate on these without some sort of regridding or binning (which is what https://github.com/JiaweiZhuang/cubedsphere/blob/master/cubedsphere/util.py does if I understood this right).

Here is a plot of the physical longitude of one of the polar faces:
![polar_cap](https://user-images.githubusercontent.com/7556347/103618418-3b7cef00-4f30-11eb-80ad-e4078a1186e4.png)

> Those sort of operations are currently out of scope for xgcm, at least in my opinion. But it would be nice to have a workflow that uses e.g. xESMF to regrid to a regular lon/lat grid, and then operate seamlessly with xgcm. If that is something you would consider I think that an example of something like what you are doing would go a long way. We can then see where things cause friction.

I had the same idea and I am therefore currently working on a small python package ([cubedsphere](https://github.com/aaronDavidSchneider/cubedsphere)). My idea is to use `xgcm` to interpolate interface quantities to the cell centre (This works. I hope the results are also physically correct?) and regrid afterwards using `xESMF`.

I got this already working (see here: https://github.com/AaronDavidSchneider/cubedsphere/blob/main/cubedsphere/regrid.py).

It should then be no problem to use `xgcm` on the regridded dataset.

**Comment by raphaeldussin** [comment]
@AaronDavidSchneider I have an idea for the regridding from CS to a logically rectangular grid: since ESMF basically create a sparse matrix between two vectors of grid cells, you may be able to regrid the CS data by concatenating your faces of data along one of the horizontal dimensions (lon or lat). Just make sure you set periodic to False. There may be some other options more hidden in the ESMF API, I'd be happy to help.

**Comment by AaronDavidSchneider** [comment]
Thanks @raphaeldussin for your ideas! I think I have got the regridding part working.
I do so by creating a list of 6 xESMF-regridders (one for each face) and summing up the results afterwards.
I think this should do the same as concatenating along lon or lat?!
Have a look at https://github.com/AaronDavidSchneider/cubedsphere/blob/main/cubedsphere/regrid.py.

I got it working with the MNC output files. I am currently trying to get it also working with the xmitgcm created datasets (currently dealing with conflicting namings here...)

**Comment by raphaeldussin** [comment]
Regridding each face can work if you constrain the destination grid to coincide with face boundaries but
how do you treat a destination cell overlapping between source cells from different faces? I think xESMF can work this out
for you. The current `grid` structure does not accept a `face` dimension, that's why I suggest to concat each face along one of the horizontal dimensions. Eventually all of this is gonna be flattened into a vector so this "should" work.

**Comment by AaronDavidSchneider** [comment]
I will close this issue since the discussion has moved past the question and the original question has already been answered here.
