### ISSUE TITLE
Proposal: grid_ufunc

### ISSUE THREAD

**Issue by rabernat** [xgcm/xgcm#344]
Xarray and the whole python array ecosystem has evolved considerably since the creation of xgcm. The introduction of xarray's `apply_ufunc`, dask / numba gufuncs, etc. has evolved the way we think about array code, allowing us to do complex array operations in a compact, elegant way. At the same time, we have become more aware of some of the performance limitations of xgcm, particularly with large dask arrays. This proposal is for an internal refactoring of xgcm that could address all of the above.

### Background: generatlized ufuncs

The numpy C api defines the concept of [generalized ufuncs](https://numpy.org/doc/stable/reference/c-api/generalized-ufuncs.html) (gufuncs). Dask [exposes gufuncs at the python level](https://docs.dask.org/en/latest/array-gufunc.html). Numba also allows you to write [vectorized gufuncs](https://numba.pydata.org/numba-doc/latest/user/vectorize.html#the-guvectorize-decorator).  At the core of gufuncs is the concept of a _signature_. A signature is a symbolic representation of how a function acts on a set of _core dimensions_. The specifies the required core dimensions of the inputs and how the output dimensions are related to the input dimensions. It's easiest to explain signatures through examples. Here I copy directly from the numpy docs linked above.

name | signature | common usage
-- | -- | --
add | `(),()->()` | binary ufunc
sum1d | `(i)->()` | reduction
inner1d | `(i),(i)->()` | vector-vector multiplication
matmat | `(m,n),(n,p)->(m,p)` | matrix multiplication
vecmat | `(n),(n,p)->(p)` | vector-matrix multiplication
matvec | `(m,n),(n)->(m)` | matrix-vector multiplication
matmul | `(m?,n),(n,p?)->(m?,p?)` | combination of the four above
outer_inner | `(i,t),(j,t)->(i,j)` | inner over the last dimension, outer over the second to last, and loop/broadcast over the rest.
cross1d | `(3),(3)->(3)` | cross product where the last dimension is frozen and must be 3

This syntax is used by numpy, dask, numba, and likely other parts of the pydata ecosystem do describe gufuncs.

### New idea: grid_ufunc

I think we should refactor all of xgcm's primitive operations to be gufuncs. However, we need an additional layer of complexity, because xgcm deals not just with raw dimensions but with _axes_. We could imagine generalizing the gufunc signature as follows.

name | signature
-- | -- 
diff_center_to_left(a) | `(X:center)->(X:left)`
interp_center_to_left(a) | `(X:center)->(X:left)`
diff_left_to_center(a) | `(X:left)->(Y:center)`
interp_left_to_center(a) | `(X:left)->(Y:center)`

Here `X` and `Y` are arbitrary axis names, while `center` and `left` are xgcm [axis positions](https://xgcm.readthedocs.io/en/latest/grids.html#axes-and-positions). These would be translated to core dimensions, and the low-level numerical routine eventually called via either `xr.apply_ufunc` or else with an xgcm-specific wrapper layer.

Implementing one of these functions might look like

```python
@grid_ufunc(signature="(X:center)->(X:left)")
def diff_center_to_left(a):
    return a - np.roll(a, -1)
```

Here the decorator would be taking care of all the coordinate / dimension wrapping and eventually calling the low-level numerical routine.

For the existing core xgcm routines (e.g. diff, interp), this would be overkill. But it would allow us to start implementing more complex operations. For example
```python
@grid_ufunc(signature="(X:left,Y:center),(X:center,Y:left)->(X:left,Y:left)")
def cgrid_vorticity(u, v):
    # do complicated stuff
    return vort
```
(We could also add metrics to the function and signature.)

If this existed, all of the [laplacian kernels](https://github.com/ocean-eddy-cpt/gcm-filters/blob/master/gcm_filters/kernels.py) from gcm-filters could become xgcm grid_ufuncs (cc @noraloose).

- 2D scalar Laplacian signature: `(X:center,Y:center)->(X:center,Y:center)`
- 2D c-grid vector Laplacian signature: `(X:left,Y:center),(X:center,Y:left)->(X:left,Y:center),(X:center,Y:left)`

Thoughts?

(@tomnicholas)

**Comment by dcherian** [comment]
So this function would
1. translate the signature to a list of lists for `input_core_dims`,`output_core_dims`, `output_sizes`.
1. Raise errors if provided inputs are not at the expected positions (basically join="exact")
	1. Should it be possible to opt-in to "interp" the inputs to the expected positions
1. pass the translated signature + inputs + function to `apply_ufunc`
1. Do something about `metrics` and `boundary`

I think this is a great idea!

We should do something to allow writing one function that can handle inputs at multiple points (like `diff`). This would be like how numba handles multiple dtype combinations.

**Comment by jbusecke** [comment]
This sounds very exciting and seems like it could solve many of the outstanding issues. I will have to dive in deeper to understand this in detail, but am excited to help with this. Perhaps we should organize a project around this, where we gather issues that could/should be solved by this large refactor?

**Comment by jbusecke** [comment]
One (perhaps stupid question) I had immediately: 

To preserve the existing functionality of e.g. `diff` we would need all possible diff ufuncs:

name | signature
-- | -- 
diff_center_to_left(a) | `(X:center)->(X:left)`
diff_center_to_right(a) | `(X:center)->(X:right)`
diff_center_to_outer(a) | `(X:center)->(Y:outer)`
diff_left_to_center(a) | `(X:left)->(Y:center)`
diff_left_to_inner(a) | `(X:left)->(Y:inner)`
... | ...

That seems like a lot of redundant code, or will the `signature` be generated dynamically by the existing logic?

**Comment by dcherian** [comment]
> We should do something to allow writing one function that can handle inputs at multiple points (like diff). This would be like how numba handles multiple dtype combinations.

I guess each ufunc should have an associated mapping of input locations → output locations. As long as the inputs match the provided locations, no error is raised, and we only need one function.

``` python
@grid_ufunc(signature=(
	"(X:center)->(X:left)", 
	"(X:center)->(X:right)",
	...
))
def diff(a):
	pass
```

**Comment by rabernat** [comment]
I see no problem with having a lot of different small ufuncs, since they would be very short. I don't quite see how we could support multiple different signatures for a single function as in Deepak's example.

I imagine that these grid_ufuncs would not be the high-level API for xgcm (which would ideally not change), but instead would be more of an internal thing.`Grid.diff` would still need to figure out which grid_ufunc to call based on its arguments.

**Comment by jbusecke** [comment]
Ok that makes sense to me. Thanks for clarifying.

> I imagine that these grid_ufuncs would not be the high-level API for xgcm (which would ideally not change), but instead would be more of an internal thing.

This sounds great to me! It might actually end up less code, since all the `get_left`...etc functions are quite a bit of lines haha.

**Comment by dcherian** [comment]
>  I don't quite see how we could support multiple different signatures for a single function as in Deepak's example.

Doesn't grid_ufunc look like this? Maybe I'm missing something?

```python

def validate_arguments(self, signature, args):
	valid_positions = signature_to_valid_positions(signature)
	# TODO: some loop over axes too
	for array, valid_pos in zip(args, valid_positions):
		assert self.get_position(array) in valid_pos
	

def grid_ufunc(self, function, signature, *args, kwargs):
	
	self.validate_arguments(signature, args, apply_ufunc_kwargs, kwargs)

	input_core_dims, output_core_dims = self.signature_to_core_dims(signature)
	return xr.apply_ufunc(
		  function,
		  *args,
		  input_core_dims=input_core_dims,
		  output_core_dims=output_core_dims,
		  kwargs=kwargs,
		  **apply_ufunc_kwargs,
	)
```

> these grid_ufuncs would not be the high-level API for xgcm

But it would be a public interface so that you could plug in "gcm-filters"?

**Comment by rabernat** [comment]
> Doesn't grid_ufunc look like this? Maybe I'm missing something?

Yes that's basically it. But the catch is that `function` will be different for different signatures. For example.

```python
@grid_ufunc(signature="(X:center)->(X:left)")
def diff_center_to_left(a):
    return a - np.roll(a, -1)

@grid_ufunc(signature="(X:center)->(X:right)")
def diff_center_to_left(a):
    return np.roll(a, 1) - a
```

That's why I don't think it's possible to define a single `diff` grid_ufunc that works with multiple different signatures without an extra layer of dispatch. Maybe _I'm_ missing something?

> But it would be a public interface so that you could plug in "gcm-filters"?

Haven't quite worked this out yet, but yes, ideally the decorator would be public and users could define custom grid ufuncs.

**Comment by dcherian** [comment]
ah yes you are right. I was thinking of `interp`

**Comment by TomNicholas** [comment]
This isn't stale. 

I think #362 is ready for another review? The next step should be to either try to generalise the decorator in #362 to handle metrics and boundaries, or to try refactoring the core xgcm code using the decorator.

I tried the latter yesterday but got a bit confused because the basic grid operations currently don't seem to actually change the axes? For example `.diff` ultimately just calls `f` on left- and right-hand data, but never checks or changes what the axis positions of the input variables are (at least not if you're ignoring boundaries). Does that mean that the refactored version of this function would create a signature based on the input, and then parse that signature immediately? i.e. no dispatching to different functions for different signatures like we discussed above?

**Comment by rabernat** [comment]
I recently found this paper 


> ### Verifying Spatial Properties of Array Computations
> 
> Dominic, Orchard, Mistral, Contrastin, Matthew, Danish, Andrew, Rice (2017) Verifying Spatial Properties of Array Computations. Journal of Proceedings of the ACM on Programming Languages, 1 (OOPSLA). Article Number 75. ISSN 2475-1421. E-ISSN 2475-1421. (doi:10.1145/3133899) (KAR id:62274)
> http://dx.doi.org/10.1145/3133899
> 
> Arrays computations are at the core of numerical modelling and computational science applications. However, low-level manipulation of array indices is a source of program error. Many practitioners are aware of the need to ensure program correctness, yet very few of the techniques from the programming research community are applied by scientists. We aim to change that by providing targetted lightweight verification techniques for scientific code. We focus on the all too common mistake of array offset errors as a generalisation of off-by-one errors. Firstly, we report on a code analysis study on eleven real-world computational science code base, identifying common idioms of array usage and their spatial properties. This provides much needed data on array programming idioms common in scientific code. From this data, we designed a lightweight declarative specification language capturing the majority of array access patterns via a small set of combinators. We detail a semantic model, and the design and implementation of a verification tool for our specification language, which both checks and infers specifications. We evaluate our tool on our corpus of scientific code and give verification case studies of bug fixes that are detected by our approach. We found roughly 80,000 targets for specification across roughly 1.4 million lines of code, showing that the vast majority of array computations read from arrays in a pattern with a simple, regular, static shape.

https://kar.kent.ac.uk/62274/

There are some useful concepts in there for the grid_ufunc project.

cc @cmdupuis3 who will probably find this stuff interesting.

**Comment by TomNicholas** [comment]
On Friday @rabernat suggested using type hints to encode the grid ufunc signatures instead of putting that info in the decorator. I like this idea because I think it's neater, but wondered what others thought. 

One simple way to do it would be like this:
```python
from typing import Annotated

@grid_ufunc
def diff_center_to_left(
    a: Annotated[DataArray, "X:center"]
) -> Annotated[DataArray, "X:left"]:

    return a - np.roll(a, -1)
```
where we can extract the annotation of the type hint like this:
```python
from typing import get_type_hints

def get_grid_signatures(func):
    hints = get_type_hints(diff_center_to_left, include_extras=True)

    print({name: hint.__metadata__ for name, hint in hints.items()})


get_grid_signatures(diff_center_to_left)
```
which prints
`{'a': ('X:center',), 'return': ('X:left',)}`

Then all I have to do is put `get_grid_signatures` in the decorator and we no longer need the `signature` argument at all! This seems neater: per-variable grid information is passed right next to that variable, whereas function-level information goes in the function decorator.

The advantage of using `typing.Annotated` is that it still works with `mypy`: the static type checker only sees `DataArray` in this case. (And if you don't have mypy installed then the annotation still works, just the types are never statically checked.)

Generally though we need to decide how we want our decorated ufuncs to work with `mypy`. It's a weird case because our decorator is changing the expected type of the function's arguments, from numpy to xarray. We can:
1) Type hint the function args with the type the undecorated function accepts (i.e. `np.ndarray`). This would mean the type in the function signature was consistent with the code in the body of the function.
2) Type hint the function args with the type the decorated function accepts (i.e. `xr.DataArray`, like I did above). This would mean the type in the function signature was consistent with what the user actually needs to pass to the decorated function.
3) Just disable type checking entirely on decorated functions, by using `typing.no_type_check`, so mypy will ignore these functions. Then we don't even need `Annotated`, because we could pass whatever we liked as a type hint, and we just wouldn't bother stating if it's a numpy array or DataArray, as the argument type is assumed to be explained in the docs for `@grid_ufunc`. The disadvantage of this is that then we lose the benefits of static type checking on all the function's arguments (I think you can't turn mypy off on a per-variable basis either).

I think we still should make this type behaviour decision even if we don't go for the grid-info-in-type-hints approach.

Thoughts?

**Comment by rabernat** [comment]
I vote for option 1. It will make it most clear to authors of grid_ufuncs that their function must indeed consume and produce numpy arrays.

The decorator could always modify (or simply remove) the annotations while compiling the grid ufunc to avoid confusion downstream.

**Comment by TomNicholas** [comment]
What should the syntax be for `apply_as_grid_ufunc`? In my current API that function is an alternative, which gets passed the ufunc (like `xr.apply_ufunc`) rather than decorating it. This means I could type hint the input variables (like below), but I can't type hint the return value.

```python
da: Gridded[xr.DataArray, "X:center"]
result = apply_as_grid_ufunc(
    diff_center_to_left,
    da,
    axis=[("depth",)],
    grid=grid,
)
```

Whilst the decorator approach works well, this seems kind of awkward. My options are:
1) Add another kwarg to `apply_as_grid_ufunc` whose type hint specifies the grid info (it can't be called `return` though because that's a reserved name in python),
2) Keep `apply_as_grid_ufunc` how it currently is, expecting a `signature` argument of a form like `"(X:center)->(X:inner)"`,
3) Remove `apply_as_grid_ufunc` from the API entirely in favour of just using the decorator.

**Comment by TomNicholas** [comment]
> What should the syntax be for apply_as_grid_ufunc?

I think I'm just going to leave the `signature` argument in there, but have it be optional. Then raise an error if the user attempts to mix annotated type hints with the signature argument, only allowing one or the other.
