### ISSUE TITLE
`open_mdsdataset`: Can't data read files Boo-T.*

### ISSUE THREAD

**Issue by jklymak** [xgcm/xgcm#41]
I have some files called ` KLeps-T.0000000720.data`, which are time-averaged versions of a package's output.  `KLeps` was in `available_diagnostics.log`, so to fix this, I simply added an entry into `all_diags` with the average indicator.  

Seems to work fine now.

This is after line 280 in `mdsxray.py`.  Please forgive me for not doing a full pull-request for a one-liner!

```python
                all_diags[key] = (coords, desc, units)
                all_diags[key+'-T'] = (coords, desc, units)
```

**Comment by rabernat** [comment]
Can you tell me the contents of `KLeps-T.0000000720.data`?

**Comment by jklymak** [comment]
It's an averaged dissipation rate from my kl10 package.  

Cheers.  Jody.

**Comment by jklymak** [comment]
Sorry, the actual contents are 
```
nDims = [   3 ];
 dimList = [
  1024,    1, 1024,
   256,    1,  256,
   400,    1,  400
 ];
 dataprec = [ 'float64' ];
 nrecords = [     1 ];
 timeStepNumber = [        720 ];
```

These contents are exactly the same as `KLeps.0000000720.meta` but represent the time-averaged value.  I get them by setting `KLtaveFreq` in `data.kl10` (instead of `KLdumpFreq`).  I think all the mds outputs behave this way.

**Comment by rabernat** [comment]
From this meta file, I gather you are not actually outputting this via `data.diagnostics` but instead are using the "native" output of your package.

This is a use case I had not anticipated. (It is also basically just a coincidence that the `KLeps` file has the same name as the entry in `data.diagnostics`.)

I think a better solution would be to add all of the metadata for the native output of your package around here:
https://github.com/xgcm/xgcm/blob/master/xgcm/mdsxray.py#L141
(This is something that needs to be done for lots of other packages as well...exf, kpp, etc.)

However, I would hold off on doing that for the moment. I am currently refactoring this code heavily in order to accomodate the LLC grids. Better to deal with this after that is complete.

Sounds like your temporary fix works for you for now, right?

**Comment by jklymak** [comment]
Oh.  Hmm... Well, I guess you are right.  Somehow we went to the bother of adding KL10 diagnostics (`pkg/kl10/kl10_diagnostics_init.F`) but I don't use diagnostics, so I was just using the native output.  So you are absolutely correct that it is a co-incidence.  Coding it in at L141 seems fair enough. 

Alternatively, you could somehow parse all the *.meta files you find.  That may require some guessing as to what the proper dimensions are?  

What I have works fine for now.  I should probably just start using the diagnostics package, particularly as I am changing my output anyways.

**Comment by rabernat** [comment]
@jklymak I just wanted to give you a heads up that I have moved all of the mitgcm-specific features of xgcm into a new package called xgcm:
https://github.com/xgcm/xmitgcm
This move also includes a major refactor of the code. I am closing the mitgcm-specific issues here, but I would really appreciate your input on the new package.

xgcm is going back to it's original mission: implementing finite-volume differential and integral operations on GCM grids (which is not specific to mitgcm).
