### ISSUE TITLE
Coordinate parsing module

### ISSUE THREAD

**Issue by jbusecke** [xgcm/xgcm#75]
I have used xgcm successfully with MITgcm output but am now working with MOM5/6 output and plan to use xgcm heavily. 

It is easy enough to manually add the required comodo attributes to an existing xarray.Dataset but since the notation is usually the same within each model I propose to automate this.

As I am thinking of it right now it would basically provide a convenient way of parsing the attributes to the corresponding xarray coordinates like this:

'''
ds_compatible = parse_coordinates(ds, x_axis_grid_coord='something_longitude', x_axis_cell_coord='somethingelse_longitude')
'''

Over time users of different gcms could add dictionaries in the code with the corresponding coordinate names, which would enable a simple use case lile this:
'''
ds_compatible = parse_coords(ds, config='MOM6')
'''

I think in the long run this could help expanding the userbase of xgcm and save a lot of typing or copy-pasting. 

What does everybody here think?

**Comment by spencerahill** [comment]
>Over time users of different gcms could add dictionaries in the code with the corresponding coordinate names

This is similar to the approach we've taken in [aospy](https://aospy.readthedocs.io) to enable automated calculations across different models, etc.  However, your suggestion differs in terms of bundling the variable names on a per-model basis.  In contrast, aospy defines default names for each coordinate, and then simply has a list of potential candidate names that it searches for for each one.  This is all located in the [`internal_names.py`](https://github.com/spencerahill/aospy/blob/develop/aospy/internal_names.py) module.  (We do the same for variable names via the `name` and `alt_names` attrs of our [`Var`](https://github.com/spencerahill/aospy/blob/develop/aospy/var.py) class).

One upside to your approach is that, unlike ours, there is no problem if two different models use the same name to refer to different things.  Our approach relies on this not happening; otherwise it might grab the wrong coordinate if the name is coordinate-ambiguous across models.

Nevertheless, we have found defining a set of internal names that we rename everything to to be really useful.  The two approaches aren't mutually exclusive -- you could e.g. just pick MITgcm's names as the ones you use.  Maybe this is already what you had in mind?

**Comment by jbusecke** [comment]
Thanks @spencerahill, I will definitely have to check out aospy in more depth! It looks really cool!

I think for the sake of consistency (and my current need for this feature in my project) I would prefer to keep this parsing to work on the attributes instead of the variable names. It might however be worth exploring if we can 'translate' these back to aospy compatible names. 

My primary goal with this is to advance xgcm, to be able to use the existing grid structure to compute vector calculus operators used for budget calculations, like gradient, divergence etc. 'under the hood', so that the user doesn't have to worry about the grid structure once it is initialized in xgcm. 

Maybe that is a functionality that could be implemented into aospy later? I did not see calculations for those operators in aospy (but I might just not have looked properly, this has been one long week! Also I am not sure if that is outside of the scope of aospy). 

@rabernat , can we maybe hash out a desired functional structure? That would help me to get started with this.

**Comment by spencerahill** [comment]
Sorry I wasn't clear.  I wasn't suggesting that you use aospy or somehow integrate this with aospy.  I am interested in this functionality in xgcm for other reasons (see https://github.com/pangeo-data/pangeo/issues/1 and https://github.com/xgcm/xgcm/issues/73) and was merely offering my $0.02 on how we have approached similar issues of supporting different names across models etc 😄

**Comment by jbusecke** [comment]
Should I close this? #93 supposedly took care of it?
