### ISSUE TITLE
cubed-sphere exchanges

### ISSUE THREAD

**Issue by rabernat** [xgcm/xgcm#76]
Many models (e.g. MITgcm, GEOS, GFDL FV3) use "tiles" or "faces" of locally orthogonal curvilinear grids which are connected at the tile faces.

![MITgcm cubed sphere grid](http://www.ecco-group.org/images/gridlines-llc.jpg)

In xmitgcm, for example, each face is a dimension: variables have dimensions of `('time', 'k', 'face', 'j', 'i')`. For xgcm to difference and and interpolate correctly on such models, it needs a way to exchange data across the tile faces.

I have created a prototype for doing these exchanges via an xarray decorator in this gist:
https://gist.github.com/rabernat/6c18194ec55ca46b0139f33a9a9f805a

It would not be super hard to add this functionality to xgcm. (Special logic would be needed for vectors.) This would enable xgcm to work "out of the box" on such datasets.

cc @jetesdal, @maikejulie, @darothen

**Comment by rabernat** [comment]
@maikejulie, following up on our email discussion, I do indeed have a prototype for doing the cubed-sphere / llc tile exchanges. It is in this gist:
https://gist.github.com/rabernat/6c18194ec55ca46b0139f33a9a9f805a

Running this code gives all xarray objects a method called `.exch.shift_face()`, which does what it sounds like. The signature and docstring for this method is repeated below:
```
        def shift_face(self, **shifts)

        """Shift this dataarray by an offset along one or more horizontal
        dimensions, properly accounting for face topology links.
        Woks only on variables, not coordinates. The
        direction of rotation is consistent with :py:func:`numpy.roll`.
        Parameters
        ----------
        **shifts : keyword arguments of the form {dim: offset}
            Integer offset to shift each of the given dimensions. Positive
            offsets shift to the right; negative offsets shift to the left.
        Returns
        -------
        shifted : Dataset
            Dataset with the same coordinates and attributes but shifted
            variables.
        See also
        --------
        roll
        shift
        """
```

What i have not done (in over one year since I first developed this) is actually incorporate it into xgcm. But as I said above, that is not a huge amount of work.

**Comment by maikejulie** [comment]
Excellent Ryan. Thanks for pointing this out again. I think this is a
really great place to continue working!

Do you think you have time to incorporate it into xmitgcm?

Best,
Maike


On 19 Nov 2017 5:07 pm, "Ryan Abernathey" <notifications@github.com> wrote:

@maikejulie <https://github.com/maikejulie>, following up on our email
discussion, I do indeed have a prototype for doing the cubed-sphere / llc
tile exchanges. It is in this gist:
https://gist.github.com/rabernat/6c18194ec55ca46b0139f33a9a9f805a

Running this code gives all xarray objects a method called
.exch.shift_face(), which does what it sounds like. The signature and
docstring for this method is repeated below:

        def shift_face(self, **shifts)

        """Shift this dataarray by an offset along one or more horizontal
        dimensions, properly accounting for face topology links.
        Woks only on variables, not coordinates. The
        direction of rotation is consistent with :py:func:`numpy.roll`.
        Parameters
        ----------
        **shifts : keyword arguments of the form {dim: offset}
            Integer offset to shift each of the given dimensions. Positive
            offsets shift to the right; negative offsets shift to the left.
        Returns
        -------
        shifted : Dataset
            Dataset with the same coordinates and attributes but shifted
            variables.
        See also
        --------
        roll
        shift
        """

What i have not done (in over one year since I first developed this) is
actually incorporate it into xgcm. But as I said above, that is not a huge
amount of work.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/xgcm/xgcm/issues/76#issuecomment-345553903>, or mute
the thread
